// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mu_values.proto

#ifndef PROTOBUF_INCLUDED_mu_5fvalues_2eproto
#define PROTOBUF_INCLUDED_mu_5fvalues_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_mu_5fvalues_2eproto 

namespace protobuf_mu_5fvalues_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_mu_5fvalues_2eproto
namespace willand_description {
class MuValues;
class MuValuesDefaultTypeInternal;
extern MuValuesDefaultTypeInternal _MuValues_default_instance_;
}  // namespace willand_description
namespace google {
namespace protobuf {
template<> ::willand_description::MuValues* Arena::CreateMaybeMessage<::willand_description::MuValues>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace willand_description {

// ===================================================================

class MuValues : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:willand_description.MuValues) */ {
 public:
  MuValues();
  virtual ~MuValues();

  MuValues(const MuValues& from);

  inline MuValues& operator=(const MuValues& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MuValues(MuValues&& from) noexcept
    : MuValues() {
    *this = ::std::move(from);
  }

  inline MuValues& operator=(MuValues&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MuValues& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MuValues* internal_default_instance() {
    return reinterpret_cast<const MuValues*>(
               &_MuValues_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MuValues* other);
  friend void swap(MuValues& a, MuValues& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MuValues* New() const final {
    return CreateMaybeMessage<MuValues>(NULL);
  }

  MuValues* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MuValues>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MuValues& from);
  void MergeFrom(const MuValues& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MuValues* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double mu_sim_l = 1;
  void clear_mu_sim_l();
  static const int kMuSimLFieldNumber = 1;
  double mu_sim_l() const;
  void set_mu_sim_l(double value);

  // double mu_sim_r = 2;
  void clear_mu_sim_r();
  static const int kMuSimRFieldNumber = 2;
  double mu_sim_r() const;
  void set_mu_sim_r(double value);

  // double mu_model_l = 3;
  void clear_mu_model_l();
  static const int kMuModelLFieldNumber = 3;
  double mu_model_l() const;
  void set_mu_model_l(double value);

  // double mu_model_r = 4;
  void clear_mu_model_r();
  static const int kMuModelRFieldNumber = 4;
  double mu_model_r() const;
  void set_mu_model_r(double value);

  // @@protoc_insertion_point(class_scope:willand_description.MuValues)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double mu_sim_l_;
  double mu_sim_r_;
  double mu_model_l_;
  double mu_model_r_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mu_5fvalues_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MuValues

// double mu_sim_l = 1;
inline void MuValues::clear_mu_sim_l() {
  mu_sim_l_ = 0;
}
inline double MuValues::mu_sim_l() const {
  // @@protoc_insertion_point(field_get:willand_description.MuValues.mu_sim_l)
  return mu_sim_l_;
}
inline void MuValues::set_mu_sim_l(double value) {
  
  mu_sim_l_ = value;
  // @@protoc_insertion_point(field_set:willand_description.MuValues.mu_sim_l)
}

// double mu_sim_r = 2;
inline void MuValues::clear_mu_sim_r() {
  mu_sim_r_ = 0;
}
inline double MuValues::mu_sim_r() const {
  // @@protoc_insertion_point(field_get:willand_description.MuValues.mu_sim_r)
  return mu_sim_r_;
}
inline void MuValues::set_mu_sim_r(double value) {
  
  mu_sim_r_ = value;
  // @@protoc_insertion_point(field_set:willand_description.MuValues.mu_sim_r)
}

// double mu_model_l = 3;
inline void MuValues::clear_mu_model_l() {
  mu_model_l_ = 0;
}
inline double MuValues::mu_model_l() const {
  // @@protoc_insertion_point(field_get:willand_description.MuValues.mu_model_l)
  return mu_model_l_;
}
inline void MuValues::set_mu_model_l(double value) {
  
  mu_model_l_ = value;
  // @@protoc_insertion_point(field_set:willand_description.MuValues.mu_model_l)
}

// double mu_model_r = 4;
inline void MuValues::clear_mu_model_r() {
  mu_model_r_ = 0;
}
inline double MuValues::mu_model_r() const {
  // @@protoc_insertion_point(field_get:willand_description.MuValues.mu_model_r)
  return mu_model_r_;
}
inline void MuValues::set_mu_model_r(double value) {
  
  mu_model_r_ = value;
  // @@protoc_insertion_point(field_set:willand_description.MuValues.mu_model_r)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace willand_description

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_mu_5fvalues_2eproto
