# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mu_values.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mu_values.proto',
  package='willand_description',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmu_values.proto\x12\x13willand_description\"V\n\x08MuValues\x12\x10\n\x08mu_sim_l\x18\x01 \x01(\x01\x12\x10\n\x08mu_sim_r\x18\x02 \x01(\x01\x12\x12\n\nmu_model_l\x18\x03 \x01(\x01\x12\x12\n\nmu_model_r\x18\x04 \x01(\x01\x62\x06proto3')
)




_MUVALUES = _descriptor.Descriptor(
  name='MuValues',
  full_name='willand_description.MuValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mu_sim_l', full_name='willand_description.MuValues.mu_sim_l', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mu_sim_r', full_name='willand_description.MuValues.mu_sim_r', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mu_model_l', full_name='willand_description.MuValues.mu_model_l', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mu_model_r', full_name='willand_description.MuValues.mu_model_r', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['MuValues'] = _MUVALUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MuValues = _reflection.GeneratedProtocolMessageType('MuValues', (_message.Message,), dict(
  DESCRIPTOR = _MUVALUES,
  __module__ = 'mu_values_pb2'
  # @@protoc_insertion_point(class_scope:willand_description.MuValues)
  ))
_sym_db.RegisterMessage(MuValues)


# @@protoc_insertion_point(module_scope)
